version: '3.9'

services:
  frontend:
    image: ghcr.io/thomasw04/hackatum23/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    links:
      - backend

  backend:
    image: ghcr.io/thomasw04/hackatum23/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"
