version: '3.9'

services:
  frontend:
    image: hackatum-2023-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    links:
      - backend

  backend:
    image: hackatum-2023-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"
