name: Create and publish Docker images

on:
  push:
    branches: ['main', 'master']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: thomasw04/hackatum23
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker tag frontend:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest
          docker tag backend:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest
